# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shoutbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shoutbox
  
  pod 'Alamofire', '~> 4.5'
  pod 'DGElasticPullToRefresh'
  pod 'SwiftyJSON'
end
